name: Build PDF with Typst

on:
  push:
    paths:
      - '**.typ'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          tar -xf typst.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin

      - name: Install missing fonts
        run: |
          sudo apt-get update
          mkdir -p ~/.local/share/fonts

          # Instalar Junicode
          curl -L https://sourceforge.net/projects/junicode/files/latest/download -o junicode.zip
          unzip junicode.zip -d junicode_fonts
          cp junicode_fonts/*.ttf ~/.local/share/fonts/

          # Instalar Unzialishj
          curl -L https://dl.dafont.com/dl/?f=unzialish -o unzialish.zip
          unzip unzialish.zip -d unzialish_fonts
          cp unzialish_fonts/*.ttf ~/.local/share/fonts/

          # Refrescar caché de fuentes
          fc-cache -fv

      - name: List available fonts
        run: fc-list | grep -i "junicode\|unzialish"

      - name: Compile Typst to PDF
        run: typst compile prueba.typ

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: prueba
          path: prueba.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          name: Release for ${{ github.sha }}
          files: prueba.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

