name: Build PDF with Typst

on:
  push:
    paths:
      - '**.typ'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'fonts/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Docker image
        run: |
          docker build -t my-typst-image .

      - name: Compile Typst to PDF using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            my-typst-image compile prueba-concepto.typ

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: prueba-concepto
          path: prueba-concepto.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          name: Release for ${{ github.sha }}
          files: prueba-concepto.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
